#!/bin/sh
#
# jcc - compiles the .java files in src to .class files in bin

if [ "$#" != 1 ] ; then
  printf "Invalid arguments.\nTry jcc build to compile or jcc run to run.\n"
fi

if [ "$1" = "build" ] ; then

  # make sure the target directories exist. If not, make them.
  if [ ! -d "bin" ] ; then
    mkdir "bin"
    mkdir "bin/errtypes"
    mkdir "bin/app"
  fi

  # build the app package
  javac -d "bin" \
    "src/app/Switch.java" \
    "src/app/ContactManager.java"

  printf "Build complete.\n"

elif [ "$1" = "run" ] ; then
  cd "bin"
  java -cp ".:app:" "app/ContactManager"
  cd ..
else
  printf "Invalid argument: $1\n"
fi
